version: '3.1'

services:
  django:
    container_name: find_description
    image: find_descr:0.6
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/home/db.sqlite3
      - /home/irudenko/zabbix_scripts/zabbix-devices-output/data/:/home/data
      - ./config:/home/config